### ISSUE TITLE
theGraph 리서치 및 miro subgraph 배포 후 테스트

### ISSUE THREAD

**Issue by ouoabcde** [encrypt-X/miro-routing-api#4]
참고 #2 

# 파악한 사항

- /quote api 호출시 Failed to get pools from S3 for V3 on chain 713715 에러가 남
- 이 에러의 의미는 s3 버킷의 poolCache.json-713715-V3 파일에서 sei devnet 체인의 v3 정보를 읽어오려고 시도하는데, 이 파일이 s3 버킷에 존재하지 않는 상황
- s3 버킷의 poolCache.json-713715-V3 파일은 15분마다 routing-api에서 smart-order-router를 통해 subgraph에서 쿼리해와서 저장됨
- 이는 PoolCache Lambda에서 스케줄링 되어있음
- PoolCache Lambda의 로그를 보면, sei devnet 체인의 v3 subgraph가 등록되어 있지 않아서 관련 데이터를 가져오지 못해 에러가 나는 상황

# 요구사항

- [x] theGraph 리서치
- [x] theGraph에 v3-subgraph 코드 중 어디를 올리면 되는지 파악하기
- [x] v3-subgraph를 theGraph에 등록하여 active url 발급받기
- [x] smart-order-router에 subgraph url 등록
- [x] routing-api 재빌드 후 재배포

**Comment by ouoabcde** [comment]
# subgraph 빌드 후 theGraph에 배포 방법

1. subgraph.yaml 에서 컨트랙트 주소 및 startBlock 번호 세팅. network는 `sei-testnet` 이라고 해야함. (theGraph에서 지원하는 네트워크명이어야 함)
2. `graph deploy --studio encryptx-miro-dev` 로 theGraph에 배포

**Comment by dehypnosis** [comment]
@ouoabcde 
https://api.studio.thegraph.com/query/72969/encryptx-miro-dev/version/latest API가 이제 아래 주소에서 프록시됩니다.
https://api.dev.miro.finance/subgraph/graphql

public하게 사용하거나 하드코딩 할 때, 위 프록시 주소 사용 부탁드립니다.
